# Generated by Django 4.2.30 on 2026-05-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMonitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_inicial', models.FloatField(verbose_name='Nota inicial')),
                ('nota_corte_actual', models.FloatField(verbose_name='Nota del corte actual')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
            ],
            options={
                'verbose_name': 'Solicitud de Monitoria',
                'verbose_name_plural': 'Solicitudes de Monitoria',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
