# Generated by Django 4.2.30 on 2026-05-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitores', '0002_initial'),
        ('usuarios', '0001_initial'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmonitoria',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='usuarios.perfildocente', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='solicitudmonitoria',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='usuarios.perfilestudiante', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='solicitudmonitoria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='monitores.materia', verbose_name='Materia'),
        ),
        migrations.AddField(
            model_name='solicitudmonitoria',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='monitores.perfilmonitor', verbose_name='Monitor'),
        ),
    ]
