# Generated by Django 4.2.30 on 2026-05-03 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('monitores', '0002_initial'),
        ('solicitudes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudTutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_inicial', models.FloatField(verbose_name='Nota inicial')),
                ('nota_corte_actual', models.FloatField(verbose_name='Nota del corte actual')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_tutoria', to='usuarios.perfildocente', verbose_name='Docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_tutoria', to='usuarios.perfilestudiante', verbose_name='Estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_tutoria', to='monitores.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Solicitud de Tutoría',
                'verbose_name_plural': 'Solicitudes de Tutoría',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
