# Generated by Django 4.2.30 on 2026-05-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NUEVA_SOLICITUD', 'Nueva solicitud de monitoria'), ('SOLICITUD_ACEPTADA', 'Solicitud aceptada'), ('NUEVA_SESION', 'Nueva sesión agendada'), ('SESION_CANCELADA', 'Sesión cancelada'), ('NUEVA_CALIFICACION', 'Nueva calificación recibida'), ('NUEVO_MENSAJE', 'Nuevo mensaje'), ('MONITOR_APROBADO', 'Perfil de monitor aprobado'), ('GENERAL', 'General')], default='GENERAL', max_length=30, verbose_name='Tipo')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('enviado_por_correo', models.BooleanField(default=False, verbose_name='Enviado por correo')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
