# Generated by Django 4.2.30 on 2026-05-03 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmonitor',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitores_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilmonitor',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='monitores', to='monitores.materia', verbose_name='Materias que imparte'),
        ),
        migrations.AddField(
            model_name='perfilmonitor',
            name='perfil_estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_monitor', to='usuarios.perfilestudiante'),
        ),
        migrations.AddField(
            model_name='perfilmonitor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_monitor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disponibilidadmonitor',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='monitores.perfilmonitor'),
        ),
    ]
