# Generated by Django 4.2.30 on 2026-05-03 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Estrellas (1-5)')),
                ('comentario_privado', models.TextField(blank=True, verbose_name='Comentario privado (solo docente)')),
                ('nota_final', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Nota final')),
                ('puntaje_hake', models.FloatField(default=0.0, verbose_name='Puntaje Hake')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de calificación')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
