# Generated by Django 4.2.30 on 2026-05-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitores', '0001_initial'),
        ('calificaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to='usuarios.perfilestudiante', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to='monitores.perfilmonitor', verbose_name='Monitor'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='solicitudes.solicitudmonitoria', verbose_name='Solicitud'),
        ),
    ]
