# Generated by Django 4.2.30 on 2026-05-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('duracion_minutos', models.PositiveIntegerField(default=60, verbose_name='Duración (minutos)')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], max_length=10, verbose_name='Modalidad')),
                ('url_teams', models.URLField(blank=True, verbose_name='URL Teams')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=15, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
