# Generated by Django 4.2.30 on 2026-05-03 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('monitores', '0002_initial'),
        ('sesiones', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado')], max_length=10, verbose_name='Día')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('AMBAS', 'Presencial y Virtual')], max_length=10, verbose_name='Modalidad')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación / Enlace')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='usuarios.perfildocente', verbose_name='Docente')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disponibilidades_docente', to='monitores.materia', verbose_name='Materia (opcional)')),
            ],
            options={
                'verbose_name': 'Disponibilidad Docente',
                'verbose_name_plural': 'Disponibilidades Docente',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
