# Generated by Django 4.2.30 on 2026-05-03 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mensajes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remitente'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='solicitudes.solicitudmonitoria', verbose_name='Solicitud'),
        ),
    ]
